package numbers;

public enum Request {
    EMPTY,
    INVALID_FIRST_NUMBER,
    INVALID_SECOND_NUMBER,
    INVALID_PROPERTY,
    INVALID_ALL_PROPERTY,
    ZERO,
    FIRST_NUMBER,
    SECOND_NUMBER,
    PROPERTY,
    MUTUALLY_EXCLUSIVE
}
